<?php
ale_demo_media::add_image_to_media_gallery('ale_img1',"http://alethemes.com/olins_base/media/bakery/1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img2',"http://alethemes.com/olins_base/media/bakery/2.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img3',"http://alethemes.com/olins_base/media/bakery/3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img4',"http://alethemes.com/olins_base/media/bakery/4.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img5',"http://alethemes.com/olins_base/media/bakery/5.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img6',"http://alethemes.com/olins_base/media/bakery/6.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img7',"http://alethemes.com/olins_base/media/bakery/7.jpg");
ale_demo_media::add_image_to_media_gallery('ale_img8',"http://alethemes.com/olins_base/media/bakery/8.jpg");